services:
  social-linkapp:
    image: mongo:5
    container_name: socialink-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
# note:
# -27017:27017 means that i want to comunicate the port 27017 from my computer with container port 27017
#  ./mongo:/data/db is where we going to storage the information and this create a binding between the container and this folder
